database: "mysql"

################################################
#                                              #
#              MySQL connection                #
#   .!.                                 .!.    #
################################################

mysql:
  host: "localhost"
  port: 3306
  database: "elpomoika"
  username: "admin"
  password: "1234"